/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as WithAuthRouteImport } from './routes/_with-auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as WithAuthWithOrgRouteImport } from './routes/_with-auth/_with-org/route'
import { Route as WithAuthWithOrgWorkspaceRouteImport } from './routes/_with-auth/_with-org/workspace/route'

// Create Virtual Routes

const WithAuthOrganizationSelectorRouteLazyImport = createFileRoute(
  '/_with-auth/organization-selector',
)()
const WithAuthOnboardNewOrgRouteLazyImport = createFileRoute(
  '/_with-auth/onboard-new-org',
)()

// Create/Update Routes

const LoginRouteRoute = LoginRouteImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const WithAuthRouteRoute = WithAuthRouteImport.update({
  id: '/_with-auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WithAuthOrganizationSelectorRouteLazyRoute =
  WithAuthOrganizationSelectorRouteLazyImport.update({
    path: '/organization-selector',
    getParentRoute: () => WithAuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_with-auth/organization-selector/route.lazy').then(
      (d) => d.Route,
    ),
  )

const WithAuthOnboardNewOrgRouteLazyRoute =
  WithAuthOnboardNewOrgRouteLazyImport.update({
    path: '/onboard-new-org',
    getParentRoute: () => WithAuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_with-auth/onboard-new-org/route.lazy').then(
      (d) => d.Route,
    ),
  )

const WithAuthWithOrgRouteRoute = WithAuthWithOrgRouteImport.update({
  id: '/_with-org',
  getParentRoute: () => WithAuthRouteRoute,
} as any)

const WithAuthWithOrgWorkspaceRouteRoute =
  WithAuthWithOrgWorkspaceRouteImport.update({
    path: '/workspace',
    getParentRoute: () => WithAuthWithOrgRouteRoute,
  } as any).lazy(() =>
    import('./routes/_with-auth/_with-org/workspace/route.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_with-auth': {
      preLoaderRoute: typeof WithAuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/_with-auth/_with-org': {
      preLoaderRoute: typeof WithAuthWithOrgRouteImport
      parentRoute: typeof WithAuthRouteImport
    }
    '/_with-auth/onboard-new-org': {
      preLoaderRoute: typeof WithAuthOnboardNewOrgRouteLazyImport
      parentRoute: typeof WithAuthRouteImport
    }
    '/_with-auth/organization-selector': {
      preLoaderRoute: typeof WithAuthOrganizationSelectorRouteLazyImport
      parentRoute: typeof WithAuthRouteImport
    }
    '/_with-auth/_with-org/workspace': {
      preLoaderRoute: typeof WithAuthWithOrgWorkspaceRouteImport
      parentRoute: typeof WithAuthWithOrgRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  WithAuthRouteRoute.addChildren([
    WithAuthWithOrgRouteRoute.addChildren([WithAuthWithOrgWorkspaceRouteRoute]),
    WithAuthOnboardNewOrgRouteLazyRoute,
    WithAuthOrganizationSelectorRouteLazyRoute,
  ]),
  LoginRouteRoute,
])

/* prettier-ignore-end */
