/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace/route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WorkspaceRouteRoute = WorkspaceRouteImport.update({
  path: '/workspace',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/workspace/route.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/workspace': {
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  WorkspaceRouteRoute,
])

/* prettier-ignore-end */
