name = "croak-crud"
compatibility_date = "2023-01-01"
node_compat = true
account_id = "5ac5081163a705fd39c6647be55dcfce"
workers_dev = false
main = 'src/worker.ts'

kv_namespaces = [
  {binding = "GLOBAL_KV", id = "8a4938ab6184480bae23c6f36777cc42", preview_id="14461fe9834a4136ae280dc352ea78ba"}
]

[triggers]
crons = ["* * * * *"]

[durable_objects]
bindings = [{name = "CROAK_DURABLE_OBJECT", class_name = "CroakDurableObject"}]

[ai]
binding = "cloudflareAI"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["CroakDurableObject"]