name = "croak-crud"
compatibility_date = "2023-01-01"
node_compat = true
account_id = "5ac5081163a705fd39c6647be55dcfce"
workers_dev = false
main = 'src/worker.ts'

[triggers]
crons = ["* * * * *"]

[durable_objects]
bindings = [{name = "CROAK_DURABLE_OBJECT", class_name = "CroakDurableObject"}]

[ai]
binding = "cloudflareAI"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["CroakDurableObject"]