packages:
  - apps/expo
  - apps/nextjs
  - apps/landing-site
  - packages/api/fastify-crud
  - packages/api/fastify-ai
  - packages/db
  - packages/shared-functions
  - packages/ui
  - packages/lottie-animations
