packages:
  - apps/expo
  - apps/nextjs
  - apps/landing-site
  - packages/api/trpc
  - packages/api/fastify
  - packages/db
  - packages/shared-functions
  - packages/ui
  - packages/lottie-animations
