packages:
  - apps/tauri-vite
  - packages/hooks/websocket
  - packages/api/fastify-crud
  - packages/api/fastify-ai
  - packages/api/hono-crud
  - packages/db
  - packages/shared-functions
  - packages/ui
  - packages/lottie-animations
