import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@acme/ui/styles/globals.css";
import Providers from "./providers";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Suspense fallback={<>Loading Suspense From Layout...</>}>
            {children}
          </Suspense>
        </body>
      </Providers>
    </html>
  );
}
